# SOMECLOUD
ID: yjs7658@gmail.com
PW: ydi1234!
PATH_EXCEL: '/Users/yj/YDI_ISSUE/data/excel'
PATH_RESULT: '/Users/yj/YDI_ISSUE/data/result'
PATH_IMG: '/Users/yj/YDI_ISSUE/data/img'
TAB: 'https://cloud-svc.some.co.kr/analysisStudio/dashboard/608c7a79-78a5-49df-8d8f-c1c58e0570e9'
LOGIN: 'https://sso-cloud.some.co.kr/realms/sometrend-cloud-realm/protocol/openid-connect/auth?client_id=sometrend-cloud&redirect_uri=https://cloud-svc.some.co.kr/loginSuccess&response_mode=fragment&response_type=code&scope=openid'

# UI
OS: mac
SCRAPER_TITLE : 이슈 생애주기 분석
SCRAPER_GEO : 700x600+100+100
LOADING_GEO: 700x100+100+100
NEWS_GEO: 1000x700+200+200
CONTENT_GEO: 1000x700+300+300
VIZ_GEO : 1700x700+100+100
HEADLESS: False

# LLM
KEY: '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'
